# Generated by Django 2.2.4 on 2019-08-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
        ),
    ]
